version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: measurement_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/measurement_db?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres

volumes:
  postgres_data:
